// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/v1/lczero.proto

package lczero

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TRAINING              TaskType = 1
	TaskType_MATCH                 TaskType = 2
	TaskType_SPRT                  TaskType = 3
	TaskType_TUNING                TaskType = 4
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TRAINING",
		2: "MATCH",
		3: "SPRT",
		4: "TUNING",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TRAINING":              1,
		"MATCH":                 2,
		"SPRT":                  3,
		"TUNING":                4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_lczero_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_api_v1_lczero_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{0}
}

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_NETWORK                   ResourceType = 1
	ResourceType_BOOK                      ResourceType = 2
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "NETWORK",
		2: "BOOK",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"NETWORK":                   1,
		"BOOK":                      2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_lczero_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_api_v1_lczero_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{1}
}

type ShortOutcome int32

const (
	ShortOutcome_SHORT_OUTCOME_UNSPECIFIED ShortOutcome = 0
	ShortOutcome_WHITE_WIN                 ShortOutcome = 1
	ShortOutcome_BLACK_WIN                 ShortOutcome = 2
	ShortOutcome_DRAW                      ShortOutcome = 3
)

// Enum value maps for ShortOutcome.
var (
	ShortOutcome_name = map[int32]string{
		0: "SHORT_OUTCOME_UNSPECIFIED",
		1: "WHITE_WIN",
		2: "BLACK_WIN",
		3: "DRAW",
	}
	ShortOutcome_value = map[string]int32{
		"SHORT_OUTCOME_UNSPECIFIED": 0,
		"WHITE_WIN":                 1,
		"BLACK_WIN":                 2,
		"DRAW":                      3,
	}
)

func (x ShortOutcome) Enum() *ShortOutcome {
	p := new(ShortOutcome)
	*p = x
	return p
}

func (x ShortOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShortOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_lczero_proto_enumTypes[2].Descriptor()
}

func (ShortOutcome) Type() protoreflect.EnumType {
	return &file_api_v1_lczero_proto_enumTypes[2]
}

func (x ShortOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShortOutcome.Descriptor instead.
func (ShortOutcome) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{2}
}

type DetailedOutcome int32

const (
	DetailedOutcome_DETAILED_OUTCOME_UNSPECIFIED DetailedOutcome = 0
	DetailedOutcome_STALEMATE                    DetailedOutcome = 1
	DetailedOutcome_CHECKMATE                    DetailedOutcome = 2
	DetailedOutcome_ADJUDICATION                 DetailedOutcome = 3
	DetailedOutcome_TIMEOUT                      DetailedOutcome = 4
	DetailedOutcome_RESIGNATION                  DetailedOutcome = 5
)

// Enum value maps for DetailedOutcome.
var (
	DetailedOutcome_name = map[int32]string{
		0: "DETAILED_OUTCOME_UNSPECIFIED",
		1: "STALEMATE",
		2: "CHECKMATE",
		3: "ADJUDICATION",
		4: "TIMEOUT",
		5: "RESIGNATION",
	}
	DetailedOutcome_value = map[string]int32{
		"DETAILED_OUTCOME_UNSPECIFIED": 0,
		"STALEMATE":                    1,
		"CHECKMATE":                    2,
		"ADJUDICATION":                 3,
		"TIMEOUT":                      4,
		"RESIGNATION":                  5,
	}
)

func (x DetailedOutcome) Enum() *DetailedOutcome {
	p := new(DetailedOutcome)
	*p = x
	return p
}

func (x DetailedOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetailedOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_lczero_proto_enumTypes[3].Descriptor()
}

func (DetailedOutcome) Type() protoreflect.EnumType {
	return &file_api_v1_lczero_proto_enumTypes[3]
}

func (x DetailedOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetailedOutcome.Descriptor instead.
func (DetailedOutcome) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{3}
}

type ProgressResponse_Status int32

const (
	ProgressResponse_STATUS_UNSPECIFIED ProgressResponse_Status = 0
	ProgressResponse_ACTIVE             ProgressResponse_Status = 1 // The task is active and the client should continue working.
	ProgressResponse_CANCELLED          ProgressResponse_Status = 2 // The task has been cancelled; the client should stop.
)

// Enum value maps for ProgressResponse_Status.
var (
	ProgressResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "CANCELLED",
	}
	ProgressResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ACTIVE":             1,
		"CANCELLED":          2,
	}
)

func (x ProgressResponse_Status) Enum() *ProgressResponse_Status {
	p := new(ProgressResponse_Status)
	*p = x
	return p
}

func (x ProgressResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_lczero_proto_enumTypes[4].Descriptor()
}

func (ProgressResponse_Status) Type() protoreflect.EnumType {
	return &file_api_v1_lczero_proto_enumTypes[4]
}

func (x ProgressResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressResponse_Status.Descriptor instead.
func (ProgressResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{17, 0}
}

type CrashReport_CrashType int32

const (
	CrashReport_CRASH_TYPE_UNSPECIFIED CrashReport_CrashType = 0
	CrashReport_SIGSEGV                CrashReport_CrashType = 1
	CrashReport_INVALID_MOVE           CrashReport_CrashType = 2
	CrashReport_TIMEOUT                CrashReport_CrashType = 3
)

// Enum value maps for CrashReport_CrashType.
var (
	CrashReport_CrashType_name = map[int32]string{
		0: "CRASH_TYPE_UNSPECIFIED",
		1: "SIGSEGV",
		2: "INVALID_MOVE",
		3: "TIMEOUT",
	}
	CrashReport_CrashType_value = map[string]int32{
		"CRASH_TYPE_UNSPECIFIED": 0,
		"SIGSEGV":                1,
		"INVALID_MOVE":           2,
		"TIMEOUT":                3,
	}
)

func (x CrashReport_CrashType) Enum() *CrashReport_CrashType {
	p := new(CrashReport_CrashType)
	*p = x
	return p
}

func (x CrashReport_CrashType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrashReport_CrashType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_lczero_proto_enumTypes[5].Descriptor()
}

func (CrashReport_CrashType) Type() protoreflect.EnumType {
	return &file_api_v1_lczero_proto_enumTypes[5]
}

func (x CrashReport_CrashType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrashReport_CrashType.Descriptor instead.
func (CrashReport_CrashType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{19, 0}
}

type ClientInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                                                       // Client version (e.g., "v2.1.0")
	Hostname           string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                                     // Client's hostname
	GpuType            string                 `protobuf:"bytes,3,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`                                                                        // GPU description (e.g., "NVIDIA GeForce RTX 4090")
	GpuId              int32                  `protobuf:"varint,4,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`                                                                             // GPU device ID
	SupportedTaskTypes []TaskType             `protobuf:"varint,5,rep,packed,name=supported_task_types,json=supportedTaskTypes,proto3,enum=lczero.api.v1.TaskType" json:"supported_task_types,omitempty"` // List of supported task types
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_api_v1_lczero_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientInfo) GetGpuType() string {
	if x != nil {
		return x.GpuType
	}
	return ""
}

func (x *ClientInfo) GetGpuId() int32 {
	if x != nil {
		return x.GpuId
	}
	return 0
}

func (x *ClientInfo) GetSupportedTaskTypes() []TaskType {
	if x != nil {
		return x.SupportedTaskTypes
	}
	return nil
}

type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`                              // SHA256 hash of the uncompressed file
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                    // Primary download URL
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`      // Total file size for progress tracking
	Type          ResourceType           `protobuf:"varint,4,opt,name=type,proto3,enum=lczero.api.v1.ResourceType" json:"type,omitempty"` // Type of the resource
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`                              // Optional: format of the resource (e.g., "pgn", "epd" for books)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_api_v1_lczero_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceSpec) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ResourceSpec) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ResourceSpec) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ResourceSpec) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *ResourceSpec) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type EngineParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`                                                                                                         // Command-line arguments for the lc0 engine
	UciOptions    map[string]string      `protobuf:"bytes,2,rep,name=uci_options,json=uciOptions,proto3" json:"uci_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs for UCI options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineParams) Reset() {
	*x = EngineParams{}
	mi := &file_api_v1_lczero_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineParams) ProtoMessage() {}

func (x *EngineParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineParams.ProtoReflect.Descriptor instead.
func (*EngineParams) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{2}
}

func (x *EngineParams) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *EngineParams) GetUciOptions() map[string]string {
	if x != nil {
		return x.UciOptions
	}
	return nil
}

type BuildSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`                                                                                       // Git repository URL
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`                                                                              // Specific commit hash to check out
	BuildParams   map[string]string      `protobuf:"bytes,3,rep,name=build_params,json=buildParams,proto3" json:"build_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs for build script
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSpec) Reset() {
	*x = BuildSpec{}
	mi := &file_api_v1_lczero_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSpec) ProtoMessage() {}

func (x *BuildSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSpec.ProtoReflect.Descriptor instead.
func (*BuildSpec) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{3}
}

func (x *BuildSpec) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *BuildSpec) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *BuildSpec) GetBuildParams() map[string]string {
	if x != nil {
		return x.BuildParams
	}
	return nil
}

type TimeControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Control:
	//
	//	*TimeControl_TimeBased_
	//	*TimeControl_NodesPerMove
	Control       isTimeControl_Control `protobuf_oneof:"control"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeControl) Reset() {
	*x = TimeControl{}
	mi := &file_api_v1_lczero_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeControl) ProtoMessage() {}

func (x *TimeControl) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeControl.ProtoReflect.Descriptor instead.
func (*TimeControl) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{4}
}

func (x *TimeControl) GetControl() isTimeControl_Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *TimeControl) GetTimeBased() *TimeControl_TimeBased {
	if x != nil {
		if x, ok := x.Control.(*TimeControl_TimeBased_); ok {
			return x.TimeBased
		}
	}
	return nil
}

func (x *TimeControl) GetNodesPerMove() int64 {
	if x != nil {
		if x, ok := x.Control.(*TimeControl_NodesPerMove); ok {
			return x.NodesPerMove
		}
	}
	return 0
}

type isTimeControl_Control interface {
	isTimeControl_Control()
}

type TimeControl_TimeBased_ struct {
	TimeBased *TimeControl_TimeBased `protobuf:"bytes,1,opt,name=time_based,json=timeBased,proto3,oneof"` // Time-based control
}

type TimeControl_NodesPerMove struct {
	NodesPerMove int64 `protobuf:"varint,2,opt,name=nodes_per_move,json=nodesPerMove,proto3,oneof"` // Fixed number of nodes to search per move
}

func (*TimeControl_TimeBased_) isTimeControl_Control() {}

func (*TimeControl_NodesPerMove) isTimeControl_Control() {}

type TaskResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // Unique identifier for this task
	// Types that are valid to be assigned to Task:
	//
	//	*TaskResponse_Training
	//	*TaskResponse_Match
	//	*TaskResponse_Sprt
	//	*TaskResponse_Tuning
	Task          isTaskResponse_Task `protobuf_oneof:"task"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_api_v1_lczero_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetTask() isTaskResponse_Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskResponse) GetTraining() *TrainingTask {
	if x != nil {
		if x, ok := x.Task.(*TaskResponse_Training); ok {
			return x.Training
		}
	}
	return nil
}

func (x *TaskResponse) GetMatch() *MatchTask {
	if x != nil {
		if x, ok := x.Task.(*TaskResponse_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *TaskResponse) GetSprt() *SprtTask {
	if x != nil {
		if x, ok := x.Task.(*TaskResponse_Sprt); ok {
			return x.Sprt
		}
	}
	return nil
}

func (x *TaskResponse) GetTuning() *TuningTask {
	if x != nil {
		if x, ok := x.Task.(*TaskResponse_Tuning); ok {
			return x.Tuning
		}
	}
	return nil
}

type isTaskResponse_Task interface {
	isTaskResponse_Task()
}

type TaskResponse_Training struct {
	Training *TrainingTask `protobuf:"bytes,2,opt,name=training,proto3,oneof"`
}

type TaskResponse_Match struct {
	Match *MatchTask `protobuf:"bytes,3,opt,name=match,proto3,oneof"`
}

type TaskResponse_Sprt struct {
	Sprt *SprtTask `protobuf:"bytes,4,opt,name=sprt,proto3,oneof"`
}

type TaskResponse_Tuning struct {
	Tuning *TuningTask `protobuf:"bytes,5,opt,name=tuning,proto3,oneof"`
}

func (*TaskResponse_Training) isTaskResponse_Task() {}

func (*TaskResponse_Match) isTaskResponse_Task() {}

func (*TaskResponse_Sprt) isTaskResponse_Task() {}

func (*TaskResponse_Tuning) isTaskResponse_Task() {}

type EngineConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *BuildSpec             `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`     // Engine build specification
	Network       *ResourceSpec          `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"` // Network for the engine
	Params        *EngineParams          `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`   // Engine parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineConfiguration) Reset() {
	*x = EngineConfiguration{}
	mi := &file_api_v1_lczero_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineConfiguration) ProtoMessage() {}

func (x *EngineConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineConfiguration.ProtoReflect.Descriptor instead.
func (*EngineConfiguration) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{6}
}

func (x *EngineConfiguration) GetBuild() *BuildSpec {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *EngineConfiguration) GetNetwork() *ResourceSpec {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *EngineConfiguration) GetParams() *EngineParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type TrainingTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        *EngineConfiguration   `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`                                    // Engine and parameters for self-play
	OpeningBook   *ResourceSpec          `protobuf:"bytes,2,opt,name=opening_book,json=openingBook,proto3" json:"opening_book,omitempty"`       // Optional opening book
	NodesPerMove  int64                  `protobuf:"varint,3,opt,name=nodes_per_move,json=nodesPerMove,proto3" json:"nodes_per_move,omitempty"` // Nodes per move for training
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingTask) Reset() {
	*x = TrainingTask{}
	mi := &file_api_v1_lczero_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingTask) ProtoMessage() {}

func (x *TrainingTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingTask.ProtoReflect.Descriptor instead.
func (*TrainingTask) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{7}
}

func (x *TrainingTask) GetEngine() *EngineConfiguration {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *TrainingTask) GetOpeningBook() *ResourceSpec {
	if x != nil {
		return x.OpeningBook
	}
	return nil
}

func (x *TrainingTask) GetNodesPerMove() int64 {
	if x != nil {
		return x.NodesPerMove
	}
	return 0
}

type MatchTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Baseline      *EngineConfiguration   `protobuf:"bytes,1,opt,name=baseline,proto3" json:"baseline,omitempty"`                                // Baseline engine
	Candidate     *EngineConfiguration   `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`                              // Candidate engine
	OpeningBook   *ResourceSpec          `protobuf:"bytes,3,opt,name=opening_book,json=openingBook,proto3" json:"opening_book,omitempty"`       // Optional opening book
	NodesPerMove  int64                  `protobuf:"varint,4,opt,name=nodes_per_move,json=nodesPerMove,proto3" json:"nodes_per_move,omitempty"` // Nodes per move for matches
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchTask) Reset() {
	*x = MatchTask{}
	mi := &file_api_v1_lczero_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTask) ProtoMessage() {}

func (x *MatchTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTask.ProtoReflect.Descriptor instead.
func (*MatchTask) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{8}
}

func (x *MatchTask) GetBaseline() *EngineConfiguration {
	if x != nil {
		return x.Baseline
	}
	return nil
}

func (x *MatchTask) GetCandidate() *EngineConfiguration {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *MatchTask) GetOpeningBook() *ResourceSpec {
	if x != nil {
		return x.OpeningBook
	}
	return nil
}

func (x *MatchTask) GetNodesPerMove() int64 {
	if x != nil {
		return x.NodesPerMove
	}
	return 0
}

type SprtTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Baseline      *EngineConfiguration   `protobuf:"bytes,1,opt,name=baseline,proto3" json:"baseline,omitempty"`                          // Baseline engine configuration
	Candidate     *EngineConfiguration   `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`                        // Candidate engine configuration
	OpeningBook   *ResourceSpec          `protobuf:"bytes,3,opt,name=opening_book,json=openingBook,proto3" json:"opening_book,omitempty"` // Opening book for games
	TimeControl   *TimeControl           `protobuf:"bytes,4,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"` // Game time control
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SprtTask) Reset() {
	*x = SprtTask{}
	mi := &file_api_v1_lczero_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprtTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprtTask) ProtoMessage() {}

func (x *SprtTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprtTask.ProtoReflect.Descriptor instead.
func (*SprtTask) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{9}
}

func (x *SprtTask) GetBaseline() *EngineConfiguration {
	if x != nil {
		return x.Baseline
	}
	return nil
}

func (x *SprtTask) GetCandidate() *EngineConfiguration {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *SprtTask) GetOpeningBook() *ResourceSpec {
	if x != nil {
		return x.OpeningBook
	}
	return nil
}

func (x *SprtTask) GetTimeControl() *TimeControl {
	if x != nil {
		return x.TimeControl
	}
	return nil
}

type TuningTask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Build            *BuildSpec             `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`                                                    // Engine build specification
	Network          *ResourceSpec          `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`                                                // Network to use for all games
	OpeningBook      *ResourceSpec          `protobuf:"bytes,3,opt,name=opening_book,json=openingBook,proto3" json:"opening_book,omitempty"`                     // Optional opening book
	ParamSets        []*ParamSet            `protobuf:"bytes,4,rep,name=param_sets,json=paramSets,proto3" json:"param_sets,omitempty"`                           // A list of parameter sets to test
	TimeControl      *TimeControl           `protobuf:"bytes,5,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"`                     // Game time control
	GamesPerParamSet int32                  `protobuf:"varint,6,opt,name=games_per_param_set,json=gamesPerParamSet,proto3" json:"games_per_param_set,omitempty"` // Number of games to play for each parameter set
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TuningTask) Reset() {
	*x = TuningTask{}
	mi := &file_api_v1_lczero_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuningTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuningTask) ProtoMessage() {}

func (x *TuningTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuningTask.ProtoReflect.Descriptor instead.
func (*TuningTask) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{10}
}

func (x *TuningTask) GetBuild() *BuildSpec {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *TuningTask) GetNetwork() *ResourceSpec {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *TuningTask) GetOpeningBook() *ResourceSpec {
	if x != nil {
		return x.OpeningBook
	}
	return nil
}

func (x *TuningTask) GetParamSets() []*ParamSet {
	if x != nil {
		return x.ParamSets
	}
	return nil
}

func (x *TuningTask) GetTimeControl() *TimeControl {
	if x != nil {
		return x.TimeControl
	}
	return nil
}

func (x *TuningTask) GetGamesPerParamSet() int32 {
	if x != nil {
		return x.GamesPerParamSet
	}
	return 0
}

type ParamSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamSetId    string                 `protobuf:"bytes,1,opt,name=param_set_id,json=paramSetId,proto3" json:"param_set_id,omitempty"` // Unique ID for this parameter configuration
	Params        *EngineParams          `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`                             // The engine parameters to test
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamSet) Reset() {
	*x = ParamSet{}
	mi := &file_api_v1_lczero_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamSet) ProtoMessage() {}

func (x *ParamSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamSet.ProtoReflect.Descriptor instead.
func (*ParamSet) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{11}
}

func (x *ParamSet) GetParamSetId() string {
	if x != nil {
		return x.ParamSetId
	}
	return ""
}

func (x *ParamSet) GetParams() *EngineParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type MigrateCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateCredentialsRequest) Reset() {
	*x = MigrateCredentialsRequest{}
	mi := &file_api_v1_lczero_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateCredentialsRequest) ProtoMessage() {}

func (x *MigrateCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateCredentialsRequest.ProtoReflect.Descriptor instead.
func (*MigrateCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{12}
}

func (x *MigrateCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MigrateCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AnonymousTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymousTokenRequest) Reset() {
	*x = AnonymousTokenRequest{}
	mi := &file_api_v1_lczero_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymousTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymousTokenRequest) ProtoMessage() {}

func (x *AnonymousTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymousTokenRequest.ProtoReflect.Descriptor instead.
func (*AnonymousTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{13}
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // The authentication token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_v1_lczero_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{14}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ClientInfo    *ClientInfo            `protobuf:"bytes,2,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_api_v1_lczero_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{15}
}

func (x *TaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TaskRequest) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type ProgressReport struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Token  string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TaskId string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Progress:
	//
	//	*ProgressReport_Training
	//	*ProgressReport_Match
	//	*ProgressReport_Sprt
	//	*ProgressReport_Tuning
	Progress      isProgressReport_Progress `protobuf_oneof:"progress"`
	CrashReports  []*CrashReport            `protobuf:"bytes,7,rep,name=crash_reports,json=crashReports,proto3" json:"crash_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressReport) Reset() {
	*x = ProgressReport{}
	mi := &file_api_v1_lczero_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressReport) ProtoMessage() {}

func (x *ProgressReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressReport.ProtoReflect.Descriptor instead.
func (*ProgressReport) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{16}
}

func (x *ProgressReport) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ProgressReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProgressReport) GetProgress() isProgressReport_Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *ProgressReport) GetTraining() *TrainingProgress {
	if x != nil {
		if x, ok := x.Progress.(*ProgressReport_Training); ok {
			return x.Training
		}
	}
	return nil
}

func (x *ProgressReport) GetMatch() *MatchProgress {
	if x != nil {
		if x, ok := x.Progress.(*ProgressReport_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *ProgressReport) GetSprt() *SprtProgress {
	if x != nil {
		if x, ok := x.Progress.(*ProgressReport_Sprt); ok {
			return x.Sprt
		}
	}
	return nil
}

func (x *ProgressReport) GetTuning() *TuningProgress {
	if x != nil {
		if x, ok := x.Progress.(*ProgressReport_Tuning); ok {
			return x.Tuning
		}
	}
	return nil
}

func (x *ProgressReport) GetCrashReports() []*CrashReport {
	if x != nil {
		return x.CrashReports
	}
	return nil
}

type isProgressReport_Progress interface {
	isProgressReport_Progress()
}

type ProgressReport_Training struct {
	Training *TrainingProgress `protobuf:"bytes,3,opt,name=training,proto3,oneof"`
}

type ProgressReport_Match struct {
	Match *MatchProgress `protobuf:"bytes,4,opt,name=match,proto3,oneof"`
}

type ProgressReport_Sprt struct {
	Sprt *SprtProgress `protobuf:"bytes,5,opt,name=sprt,proto3,oneof"`
}

type ProgressReport_Tuning struct {
	Tuning *TuningProgress `protobuf:"bytes,6,opt,name=tuning,proto3,oneof"`
}

func (*ProgressReport_Training) isProgressReport_Progress() {}

func (*ProgressReport_Match) isProgressReport_Progress() {}

func (*ProgressReport_Sprt) isProgressReport_Progress() {}

func (*ProgressReport_Tuning) isProgressReport_Progress() {}

type ProgressResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        ProgressResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=lczero.api.v1.ProgressResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_api_v1_lczero_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{17}
}

func (x *ProgressResponse) GetStatus() ProgressResponse_Status {
	if x != nil {
		return x.Status
	}
	return ProgressResponse_STATUS_UNSPECIFIED
}

type GameData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrainingDataFrame []byte                 `protobuf:"bytes,1,opt,name=training_data_frame,json=trainingDataFrame,proto3" json:"training_data_frame,omitempty"`
	CompressedPgn     []byte                 `protobuf:"bytes,2,opt,name=compressed_pgn,json=compressedPgn,proto3" json:"compressed_pgn,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameData) Reset() {
	*x = GameData{}
	mi := &file_api_v1_lczero_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameData) ProtoMessage() {}

func (x *GameData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameData.ProtoReflect.Descriptor instead.
func (*GameData) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{18}
}

func (x *GameData) GetTrainingDataFrame() []byte {
	if x != nil {
		return x.TrainingDataFrame
	}
	return nil
}

func (x *GameData) GetCompressedPgn() []byte {
	if x != nil {
		return x.CompressedPgn
	}
	return nil
}

type CrashReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CrashReport_CrashType  `protobuf:"varint,1,opt,name=type,proto3,enum=lczero.api.v1.CrashReport_CrashType" json:"type,omitempty"`
	MachineInfo   string                 `protobuf:"bytes,2,opt,name=machine_info,json=machineInfo,proto3" json:"machine_info,omitempty"`                                          // Minimal, privacy-friendly machine info
	Logs          map[string][]byte      `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., "stdout", "stderr", "engine_log"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrashReport) Reset() {
	*x = CrashReport{}
	mi := &file_api_v1_lczero_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrashReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrashReport) ProtoMessage() {}

func (x *CrashReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrashReport.ProtoReflect.Descriptor instead.
func (*CrashReport) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{19}
}

func (x *CrashReport) GetType() CrashReport_CrashType {
	if x != nil {
		return x.Type
	}
	return CrashReport_CRASH_TYPE_UNSPECIFIED
}

func (x *CrashReport) GetMachineInfo() string {
	if x != nil {
		return x.MachineInfo
	}
	return ""
}

func (x *CrashReport) GetLogs() map[string][]byte {
	if x != nil {
		return x.Logs
	}
	return nil
}

type TrainingProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*GameData            `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingProgress) Reset() {
	*x = TrainingProgress{}
	mi := &file_api_v1_lczero_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingProgress) ProtoMessage() {}

func (x *TrainingProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingProgress.ProtoReflect.Descriptor instead.
func (*TrainingProgress) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{20}
}

func (x *TrainingProgress) GetGames() []*GameData {
	if x != nil {
		return x.Games
	}
	return nil
}

type MatchGame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pgn              string                 `protobuf:"bytes,1,opt,name=pgn,proto3" json:"pgn,omitempty"`
	ShortOutcome     ShortOutcome           `protobuf:"varint,2,opt,name=short_outcome,json=shortOutcome,proto3,enum=lczero.api.v1.ShortOutcome" json:"short_outcome,omitempty"`
	DetailedOutcome  DetailedOutcome        `protobuf:"varint,3,opt,name=detailed_outcome,json=detailedOutcome,proto3,enum=lczero.api.v1.DetailedOutcome" json:"detailed_outcome,omitempty"`
	CandidateIsWhite bool                   `protobuf:"varint,4,opt,name=candidate_is_white,json=candidateIsWhite,proto3" json:"candidate_is_white,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MatchGame) Reset() {
	*x = MatchGame{}
	mi := &file_api_v1_lczero_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchGame) ProtoMessage() {}

func (x *MatchGame) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchGame.ProtoReflect.Descriptor instead.
func (*MatchGame) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{21}
}

func (x *MatchGame) GetPgn() string {
	if x != nil {
		return x.Pgn
	}
	return ""
}

func (x *MatchGame) GetShortOutcome() ShortOutcome {
	if x != nil {
		return x.ShortOutcome
	}
	return ShortOutcome_SHORT_OUTCOME_UNSPECIFIED
}

func (x *MatchGame) GetDetailedOutcome() DetailedOutcome {
	if x != nil {
		return x.DetailedOutcome
	}
	return DetailedOutcome_DETAILED_OUTCOME_UNSPECIFIED
}

func (x *MatchGame) GetCandidateIsWhite() bool {
	if x != nil {
		return x.CandidateIsWhite
	}
	return false
}

type MatchProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*MatchGame           `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchProgress) Reset() {
	*x = MatchProgress{}
	mi := &file_api_v1_lczero_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchProgress) ProtoMessage() {}

func (x *MatchProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchProgress.ProtoReflect.Descriptor instead.
func (*MatchProgress) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{22}
}

func (x *MatchProgress) GetGames() []*MatchGame {
	if x != nil {
		return x.Games
	}
	return nil
}

type SprtPairReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game1         *MatchGame             `protobuf:"bytes,1,opt,name=game1,proto3" json:"game1,omitempty"`
	Game2         *MatchGame             `protobuf:"bytes,2,opt,name=game2,proto3,oneof" json:"game2,omitempty"` // The second game might not run if the first crashes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SprtPairReport) Reset() {
	*x = SprtPairReport{}
	mi := &file_api_v1_lczero_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprtPairReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprtPairReport) ProtoMessage() {}

func (x *SprtPairReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprtPairReport.ProtoReflect.Descriptor instead.
func (*SprtPairReport) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{23}
}

func (x *SprtPairReport) GetGame1() *MatchGame {
	if x != nil {
		return x.Game1
	}
	return nil
}

func (x *SprtPairReport) GetGame2() *MatchGame {
	if x != nil {
		return x.Game2
	}
	return nil
}

type SprtProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*SprtPairReport      `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	CurrentLlr    float64                `protobuf:"fixed64,2,opt,name=current_llr,json=currentLlr,proto3" json:"current_llr,omitempty"` // Current Log-Likelihood Ratio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SprtProgress) Reset() {
	*x = SprtProgress{}
	mi := &file_api_v1_lczero_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprtProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprtProgress) ProtoMessage() {}

func (x *SprtProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprtProgress.ProtoReflect.Descriptor instead.
func (*SprtProgress) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{24}
}

func (x *SprtProgress) GetPairs() []*SprtPairReport {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *SprtProgress) GetCurrentLlr() float64 {
	if x != nil {
		return x.CurrentLlr
	}
	return 0
}

type TuningPairResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game1         *MatchGame             `protobuf:"bytes,1,opt,name=game1,proto3" json:"game1,omitempty"`
	Game2         *MatchGame             `protobuf:"bytes,2,opt,name=game2,proto3,oneof" json:"game2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuningPairResult) Reset() {
	*x = TuningPairResult{}
	mi := &file_api_v1_lczero_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuningPairResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuningPairResult) ProtoMessage() {}

func (x *TuningPairResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuningPairResult.ProtoReflect.Descriptor instead.
func (*TuningPairResult) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{25}
}

func (x *TuningPairResult) GetGame1() *MatchGame {
	if x != nil {
		return x.Game1
	}
	return nil
}

func (x *TuningPairResult) GetGame2() *MatchGame {
	if x != nil {
		return x.Game2
	}
	return nil
}

type TuningParamSetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamSetId    string                 `protobuf:"bytes,1,opt,name=param_set_id,json=paramSetId,proto3" json:"param_set_id,omitempty"`
	Pairs         []*TuningPairResult    `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuningParamSetResult) Reset() {
	*x = TuningParamSetResult{}
	mi := &file_api_v1_lczero_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuningParamSetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuningParamSetResult) ProtoMessage() {}

func (x *TuningParamSetResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuningParamSetResult.ProtoReflect.Descriptor instead.
func (*TuningParamSetResult) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{26}
}

func (x *TuningParamSetResult) GetParamSetId() string {
	if x != nil {
		return x.ParamSetId
	}
	return ""
}

func (x *TuningParamSetResult) GetPairs() []*TuningPairResult {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type TuningProgress struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*TuningParamSetResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuningProgress) Reset() {
	*x = TuningProgress{}
	mi := &file_api_v1_lczero_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuningProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuningProgress) ProtoMessage() {}

func (x *TuningProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuningProgress.ProtoReflect.Descriptor instead.
func (*TuningProgress) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{27}
}

func (x *TuningProgress) GetResults() []*TuningParamSetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TimeControl_TimeBased struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseTimeSeconds  float32                `protobuf:"fixed32,1,opt,name=base_time_seconds,json=baseTimeSeconds,proto3" json:"base_time_seconds,omitempty"`
	IncrementSeconds float32                `protobuf:"fixed32,2,opt,name=increment_seconds,json=incrementSeconds,proto3" json:"increment_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimeControl_TimeBased) Reset() {
	*x = TimeControl_TimeBased{}
	mi := &file_api_v1_lczero_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeControl_TimeBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeControl_TimeBased) ProtoMessage() {}

func (x *TimeControl_TimeBased) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lczero_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeControl_TimeBased.ProtoReflect.Descriptor instead.
func (*TimeControl_TimeBased) Descriptor() ([]byte, []int) {
	return file_api_v1_lczero_proto_rawDescGZIP(), []int{4, 0}
}

func (x *TimeControl_TimeBased) GetBaseTimeSeconds() float32 {
	if x != nil {
		return x.BaseTimeSeconds
	}
	return 0
}

func (x *TimeControl_TimeBased) GetIncrementSeconds() float32 {
	if x != nil {
		return x.IncrementSeconds
	}
	return 0
}

var File_api_v1_lczero_proto protoreflect.FileDescriptor

const file_api_v1_lczero_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/lczero.proto\x12\rlczero.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xbf\x01\n" +
	"\n" +
	"ClientInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x19\n" +
	"\bgpu_type\x18\x03 \x01(\tR\agpuType\x12\x15\n" +
	"\x06gpu_id\x18\x04 \x01(\x05R\x05gpuId\x12I\n" +
	"\x14supported_task_types\x18\x05 \x03(\x0e2\x17.lczero.api.v1.TaskTypeR\x12supportedTaskTypes\"\xa0\x01\n" +
	"\fResourceSpec\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.lczero.api.v1.ResourceTypeR\x04type\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"\xaf\x01\n" +
	"\fEngineParams\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12L\n" +
	"\vuci_options\x18\x02 \x03(\v2+.lczero.api.v1.EngineParams.UciOptionsEntryR\n" +
	"uciOptions\x1a=\n" +
	"\x0fUciOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\tBuildSpec\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12L\n" +
	"\fbuild_params\x18\x03 \x03(\v2).lczero.api.v1.BuildSpec.BuildParamsEntryR\vbuildParams\x1a>\n" +
	"\x10BuildParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x01\n" +
	"\vTimeControl\x12E\n" +
	"\n" +
	"time_based\x18\x01 \x01(\v2$.lczero.api.v1.TimeControl.TimeBasedH\x00R\ttimeBased\x12&\n" +
	"\x0enodes_per_move\x18\x02 \x01(\x03H\x00R\fnodesPerMove\x1ad\n" +
	"\tTimeBased\x12*\n" +
	"\x11base_time_seconds\x18\x01 \x01(\x02R\x0fbaseTimeSeconds\x12+\n" +
	"\x11increment_seconds\x18\x02 \x01(\x02R\x10incrementSecondsB\t\n" +
	"\acontrol\"\x80\x02\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x129\n" +
	"\btraining\x18\x02 \x01(\v2\x1b.lczero.api.v1.TrainingTaskH\x00R\btraining\x120\n" +
	"\x05match\x18\x03 \x01(\v2\x18.lczero.api.v1.MatchTaskH\x00R\x05match\x12-\n" +
	"\x04sprt\x18\x04 \x01(\v2\x17.lczero.api.v1.SprtTaskH\x00R\x04sprt\x123\n" +
	"\x06tuning\x18\x05 \x01(\v2\x19.lczero.api.v1.TuningTaskH\x00R\x06tuningB\x06\n" +
	"\x04task\"\xb1\x01\n" +
	"\x13EngineConfiguration\x12.\n" +
	"\x05build\x18\x01 \x01(\v2\x18.lczero.api.v1.BuildSpecR\x05build\x125\n" +
	"\anetwork\x18\x02 \x01(\v2\x1b.lczero.api.v1.ResourceSpecR\anetwork\x123\n" +
	"\x06params\x18\x03 \x01(\v2\x1b.lczero.api.v1.EngineParamsR\x06params\"\xb0\x01\n" +
	"\fTrainingTask\x12:\n" +
	"\x06engine\x18\x01 \x01(\v2\".lczero.api.v1.EngineConfigurationR\x06engine\x12>\n" +
	"\fopening_book\x18\x02 \x01(\v2\x1b.lczero.api.v1.ResourceSpecR\vopeningBook\x12$\n" +
	"\x0enodes_per_move\x18\x03 \x01(\x03R\fnodesPerMove\"\xf3\x01\n" +
	"\tMatchTask\x12>\n" +
	"\bbaseline\x18\x01 \x01(\v2\".lczero.api.v1.EngineConfigurationR\bbaseline\x12@\n" +
	"\tcandidate\x18\x02 \x01(\v2\".lczero.api.v1.EngineConfigurationR\tcandidate\x12>\n" +
	"\fopening_book\x18\x03 \x01(\v2\x1b.lczero.api.v1.ResourceSpecR\vopeningBook\x12$\n" +
	"\x0enodes_per_move\x18\x04 \x01(\x03R\fnodesPerMove\"\x8b\x02\n" +
	"\bSprtTask\x12>\n" +
	"\bbaseline\x18\x01 \x01(\v2\".lczero.api.v1.EngineConfigurationR\bbaseline\x12@\n" +
	"\tcandidate\x18\x02 \x01(\v2\".lczero.api.v1.EngineConfigurationR\tcandidate\x12>\n" +
	"\fopening_book\x18\x03 \x01(\v2\x1b.lczero.api.v1.ResourceSpecR\vopeningBook\x12=\n" +
	"\ftime_control\x18\x04 \x01(\v2\x1a.lczero.api.v1.TimeControlR\vtimeControl\"\xd9\x02\n" +
	"\n" +
	"TuningTask\x12.\n" +
	"\x05build\x18\x01 \x01(\v2\x18.lczero.api.v1.BuildSpecR\x05build\x125\n" +
	"\anetwork\x18\x02 \x01(\v2\x1b.lczero.api.v1.ResourceSpecR\anetwork\x12>\n" +
	"\fopening_book\x18\x03 \x01(\v2\x1b.lczero.api.v1.ResourceSpecR\vopeningBook\x126\n" +
	"\n" +
	"param_sets\x18\x04 \x03(\v2\x17.lczero.api.v1.ParamSetR\tparamSets\x12=\n" +
	"\ftime_control\x18\x05 \x01(\v2\x1a.lczero.api.v1.TimeControlR\vtimeControl\x12-\n" +
	"\x13games_per_param_set\x18\x06 \x01(\x05R\x10gamesPerParamSet\"a\n" +
	"\bParamSet\x12 \n" +
	"\fparam_set_id\x18\x01 \x01(\tR\n" +
	"paramSetId\x123\n" +
	"\x06params\x18\x02 \x01(\v2\x1b.lczero.api.v1.EngineParamsR\x06params\"S\n" +
	"\x19MigrateCredentialsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x17\n" +
	"\x15AnonymousTokenRequest\"$\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"_\n" +
	"\vTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12:\n" +
	"\vclient_info\x18\x02 \x01(\v2\x19.lczero.api.v1.ClientInfoR\n" +
	"clientInfo\"\xed\x02\n" +
	"\x0eProgressReport\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12=\n" +
	"\btraining\x18\x03 \x01(\v2\x1f.lczero.api.v1.TrainingProgressH\x00R\btraining\x124\n" +
	"\x05match\x18\x04 \x01(\v2\x1c.lczero.api.v1.MatchProgressH\x00R\x05match\x121\n" +
	"\x04sprt\x18\x05 \x01(\v2\x1b.lczero.api.v1.SprtProgressH\x00R\x04sprt\x127\n" +
	"\x06tuning\x18\x06 \x01(\v2\x1d.lczero.api.v1.TuningProgressH\x00R\x06tuning\x12?\n" +
	"\rcrash_reports\x18\a \x03(\v2\x1a.lczero.api.v1.CrashReportR\fcrashReportsB\n" +
	"\n" +
	"\bprogress\"\x8f\x01\n" +
	"\x10ProgressResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.lczero.api.v1.ProgressResponse.StatusR\x06status\";\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x02\"a\n" +
	"\bGameData\x12.\n" +
	"\x13training_data_frame\x18\x01 \x01(\fR\x11trainingDataFrame\x12%\n" +
	"\x0ecompressed_pgn\x18\x02 \x01(\fR\rcompressedPgn\"\xb2\x02\n" +
	"\vCrashReport\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.lczero.api.v1.CrashReport.CrashTypeR\x04type\x12!\n" +
	"\fmachine_info\x18\x02 \x01(\tR\vmachineInfo\x128\n" +
	"\x04logs\x18\x03 \x03(\v2$.lczero.api.v1.CrashReport.LogsEntryR\x04logs\x1a7\n" +
	"\tLogsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"S\n" +
	"\tCrashType\x12\x1a\n" +
	"\x16CRASH_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSIGSEGV\x10\x01\x12\x10\n" +
	"\fINVALID_MOVE\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\"A\n" +
	"\x10TrainingProgress\x12-\n" +
	"\x05games\x18\x01 \x03(\v2\x17.lczero.api.v1.GameDataR\x05games\"\xd8\x01\n" +
	"\tMatchGame\x12\x10\n" +
	"\x03pgn\x18\x01 \x01(\tR\x03pgn\x12@\n" +
	"\rshort_outcome\x18\x02 \x01(\x0e2\x1b.lczero.api.v1.ShortOutcomeR\fshortOutcome\x12I\n" +
	"\x10detailed_outcome\x18\x03 \x01(\x0e2\x1e.lczero.api.v1.DetailedOutcomeR\x0fdetailedOutcome\x12,\n" +
	"\x12candidate_is_white\x18\x04 \x01(\bR\x10candidateIsWhite\"?\n" +
	"\rMatchProgress\x12.\n" +
	"\x05games\x18\x01 \x03(\v2\x18.lczero.api.v1.MatchGameR\x05games\"\x7f\n" +
	"\x0eSprtPairReport\x12.\n" +
	"\x05game1\x18\x01 \x01(\v2\x18.lczero.api.v1.MatchGameR\x05game1\x123\n" +
	"\x05game2\x18\x02 \x01(\v2\x18.lczero.api.v1.MatchGameH\x00R\x05game2\x88\x01\x01B\b\n" +
	"\x06_game2\"d\n" +
	"\fSprtProgress\x123\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1d.lczero.api.v1.SprtPairReportR\x05pairs\x12\x1f\n" +
	"\vcurrent_llr\x18\x02 \x01(\x01R\n" +
	"currentLlr\"\x81\x01\n" +
	"\x10TuningPairResult\x12.\n" +
	"\x05game1\x18\x01 \x01(\v2\x18.lczero.api.v1.MatchGameR\x05game1\x123\n" +
	"\x05game2\x18\x02 \x01(\v2\x18.lczero.api.v1.MatchGameH\x00R\x05game2\x88\x01\x01B\b\n" +
	"\x06_game2\"o\n" +
	"\x14TuningParamSetResult\x12 \n" +
	"\fparam_set_id\x18\x01 \x01(\tR\n" +
	"paramSetId\x125\n" +
	"\x05pairs\x18\x02 \x03(\v2\x1f.lczero.api.v1.TuningPairResultR\x05pairs\"O\n" +
	"\x0eTuningProgress\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.lczero.api.v1.TuningParamSetResultR\aresults*T\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTRAINING\x10\x01\x12\t\n" +
	"\x05MATCH\x10\x02\x12\b\n" +
	"\x04SPRT\x10\x03\x12\n" +
	"\n" +
	"\x06TUNING\x10\x04*D\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aNETWORK\x10\x01\x12\b\n" +
	"\x04BOOK\x10\x02*U\n" +
	"\fShortOutcome\x12\x1d\n" +
	"\x19SHORT_OUTCOME_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tWHITE_WIN\x10\x01\x12\r\n" +
	"\tBLACK_WIN\x10\x02\x12\b\n" +
	"\x04DRAW\x10\x03*\x81\x01\n" +
	"\x0fDetailedOutcome\x12 \n" +
	"\x1cDETAILED_OUTCOME_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTALEMATE\x10\x01\x12\r\n" +
	"\tCHECKMATE\x10\x02\x12\x10\n" +
	"\fADJUDICATION\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\x0f\n" +
	"\vRESIGNATION\x10\x052\xc2\x01\n" +
	"\vAuthService\x12[\n" +
	"\x12MigrateCredentials\x12(.lczero.api.v1.MigrateCredentialsRequest\x1a\x1b.lczero.api.v1.AuthResponse\x12V\n" +
	"\x11GetAnonymousToken\x12$.lczero.api.v1.AnonymousTokenRequest\x1a\x1b.lczero.api.v1.AuthResponse2\xa7\x01\n" +
	"\vTaskService\x12F\n" +
	"\vGetNextTask\x12\x1a.lczero.api.v1.TaskRequest\x1a\x1b.lczero.api.v1.TaskResponse\x12P\n" +
	"\x0eReportProgress\x12\x1d.lczero.api.v1.ProgressReport\x1a\x1f.lczero.api.v1.ProgressResponseB7Z5github.com/leelachesszero/lczero-server/api/v1/lczerob\x06proto3"

var (
	file_api_v1_lczero_proto_rawDescOnce sync.Once
	file_api_v1_lczero_proto_rawDescData []byte
)

func file_api_v1_lczero_proto_rawDescGZIP() []byte {
	file_api_v1_lczero_proto_rawDescOnce.Do(func() {
		file_api_v1_lczero_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_lczero_proto_rawDesc), len(file_api_v1_lczero_proto_rawDesc)))
	})
	return file_api_v1_lczero_proto_rawDescData
}

var file_api_v1_lczero_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_v1_lczero_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_v1_lczero_proto_goTypes = []any{
	(TaskType)(0),                     // 0: lczero.api.v1.TaskType
	(ResourceType)(0),                 // 1: lczero.api.v1.ResourceType
	(ShortOutcome)(0),                 // 2: lczero.api.v1.ShortOutcome
	(DetailedOutcome)(0),              // 3: lczero.api.v1.DetailedOutcome
	(ProgressResponse_Status)(0),      // 4: lczero.api.v1.ProgressResponse.Status
	(CrashReport_CrashType)(0),        // 5: lczero.api.v1.CrashReport.CrashType
	(*ClientInfo)(nil),                // 6: lczero.api.v1.ClientInfo
	(*ResourceSpec)(nil),              // 7: lczero.api.v1.ResourceSpec
	(*EngineParams)(nil),              // 8: lczero.api.v1.EngineParams
	(*BuildSpec)(nil),                 // 9: lczero.api.v1.BuildSpec
	(*TimeControl)(nil),               // 10: lczero.api.v1.TimeControl
	(*TaskResponse)(nil),              // 11: lczero.api.v1.TaskResponse
	(*EngineConfiguration)(nil),       // 12: lczero.api.v1.EngineConfiguration
	(*TrainingTask)(nil),              // 13: lczero.api.v1.TrainingTask
	(*MatchTask)(nil),                 // 14: lczero.api.v1.MatchTask
	(*SprtTask)(nil),                  // 15: lczero.api.v1.SprtTask
	(*TuningTask)(nil),                // 16: lczero.api.v1.TuningTask
	(*ParamSet)(nil),                  // 17: lczero.api.v1.ParamSet
	(*MigrateCredentialsRequest)(nil), // 18: lczero.api.v1.MigrateCredentialsRequest
	(*AnonymousTokenRequest)(nil),     // 19: lczero.api.v1.AnonymousTokenRequest
	(*AuthResponse)(nil),              // 20: lczero.api.v1.AuthResponse
	(*TaskRequest)(nil),               // 21: lczero.api.v1.TaskRequest
	(*ProgressReport)(nil),            // 22: lczero.api.v1.ProgressReport
	(*ProgressResponse)(nil),          // 23: lczero.api.v1.ProgressResponse
	(*GameData)(nil),                  // 24: lczero.api.v1.GameData
	(*CrashReport)(nil),               // 25: lczero.api.v1.CrashReport
	(*TrainingProgress)(nil),          // 26: lczero.api.v1.TrainingProgress
	(*MatchGame)(nil),                 // 27: lczero.api.v1.MatchGame
	(*MatchProgress)(nil),             // 28: lczero.api.v1.MatchProgress
	(*SprtPairReport)(nil),            // 29: lczero.api.v1.SprtPairReport
	(*SprtProgress)(nil),              // 30: lczero.api.v1.SprtProgress
	(*TuningPairResult)(nil),          // 31: lczero.api.v1.TuningPairResult
	(*TuningParamSetResult)(nil),      // 32: lczero.api.v1.TuningParamSetResult
	(*TuningProgress)(nil),            // 33: lczero.api.v1.TuningProgress
	nil,                               // 34: lczero.api.v1.EngineParams.UciOptionsEntry
	nil,                               // 35: lczero.api.v1.BuildSpec.BuildParamsEntry
	(*TimeControl_TimeBased)(nil),     // 36: lczero.api.v1.TimeControl.TimeBased
	nil,                               // 37: lczero.api.v1.CrashReport.LogsEntry
}
var file_api_v1_lczero_proto_depIdxs = []int32{
	0,  // 0: lczero.api.v1.ClientInfo.supported_task_types:type_name -> lczero.api.v1.TaskType
	1,  // 1: lczero.api.v1.ResourceSpec.type:type_name -> lczero.api.v1.ResourceType
	34, // 2: lczero.api.v1.EngineParams.uci_options:type_name -> lczero.api.v1.EngineParams.UciOptionsEntry
	35, // 3: lczero.api.v1.BuildSpec.build_params:type_name -> lczero.api.v1.BuildSpec.BuildParamsEntry
	36, // 4: lczero.api.v1.TimeControl.time_based:type_name -> lczero.api.v1.TimeControl.TimeBased
	13, // 5: lczero.api.v1.TaskResponse.training:type_name -> lczero.api.v1.TrainingTask
	14, // 6: lczero.api.v1.TaskResponse.match:type_name -> lczero.api.v1.MatchTask
	15, // 7: lczero.api.v1.TaskResponse.sprt:type_name -> lczero.api.v1.SprtTask
	16, // 8: lczero.api.v1.TaskResponse.tuning:type_name -> lczero.api.v1.TuningTask
	9,  // 9: lczero.api.v1.EngineConfiguration.build:type_name -> lczero.api.v1.BuildSpec
	7,  // 10: lczero.api.v1.EngineConfiguration.network:type_name -> lczero.api.v1.ResourceSpec
	8,  // 11: lczero.api.v1.EngineConfiguration.params:type_name -> lczero.api.v1.EngineParams
	12, // 12: lczero.api.v1.TrainingTask.engine:type_name -> lczero.api.v1.EngineConfiguration
	7,  // 13: lczero.api.v1.TrainingTask.opening_book:type_name -> lczero.api.v1.ResourceSpec
	12, // 14: lczero.api.v1.MatchTask.baseline:type_name -> lczero.api.v1.EngineConfiguration
	12, // 15: lczero.api.v1.MatchTask.candidate:type_name -> lczero.api.v1.EngineConfiguration
	7,  // 16: lczero.api.v1.MatchTask.opening_book:type_name -> lczero.api.v1.ResourceSpec
	12, // 17: lczero.api.v1.SprtTask.baseline:type_name -> lczero.api.v1.EngineConfiguration
	12, // 18: lczero.api.v1.SprtTask.candidate:type_name -> lczero.api.v1.EngineConfiguration
	7,  // 19: lczero.api.v1.SprtTask.opening_book:type_name -> lczero.api.v1.ResourceSpec
	10, // 20: lczero.api.v1.SprtTask.time_control:type_name -> lczero.api.v1.TimeControl
	9,  // 21: lczero.api.v1.TuningTask.build:type_name -> lczero.api.v1.BuildSpec
	7,  // 22: lczero.api.v1.TuningTask.network:type_name -> lczero.api.v1.ResourceSpec
	7,  // 23: lczero.api.v1.TuningTask.opening_book:type_name -> lczero.api.v1.ResourceSpec
	17, // 24: lczero.api.v1.TuningTask.param_sets:type_name -> lczero.api.v1.ParamSet
	10, // 25: lczero.api.v1.TuningTask.time_control:type_name -> lczero.api.v1.TimeControl
	8,  // 26: lczero.api.v1.ParamSet.params:type_name -> lczero.api.v1.EngineParams
	6,  // 27: lczero.api.v1.TaskRequest.client_info:type_name -> lczero.api.v1.ClientInfo
	26, // 28: lczero.api.v1.ProgressReport.training:type_name -> lczero.api.v1.TrainingProgress
	28, // 29: lczero.api.v1.ProgressReport.match:type_name -> lczero.api.v1.MatchProgress
	30, // 30: lczero.api.v1.ProgressReport.sprt:type_name -> lczero.api.v1.SprtProgress
	33, // 31: lczero.api.v1.ProgressReport.tuning:type_name -> lczero.api.v1.TuningProgress
	25, // 32: lczero.api.v1.ProgressReport.crash_reports:type_name -> lczero.api.v1.CrashReport
	4,  // 33: lczero.api.v1.ProgressResponse.status:type_name -> lczero.api.v1.ProgressResponse.Status
	5,  // 34: lczero.api.v1.CrashReport.type:type_name -> lczero.api.v1.CrashReport.CrashType
	37, // 35: lczero.api.v1.CrashReport.logs:type_name -> lczero.api.v1.CrashReport.LogsEntry
	24, // 36: lczero.api.v1.TrainingProgress.games:type_name -> lczero.api.v1.GameData
	2,  // 37: lczero.api.v1.MatchGame.short_outcome:type_name -> lczero.api.v1.ShortOutcome
	3,  // 38: lczero.api.v1.MatchGame.detailed_outcome:type_name -> lczero.api.v1.DetailedOutcome
	27, // 39: lczero.api.v1.MatchProgress.games:type_name -> lczero.api.v1.MatchGame
	27, // 40: lczero.api.v1.SprtPairReport.game1:type_name -> lczero.api.v1.MatchGame
	27, // 41: lczero.api.v1.SprtPairReport.game2:type_name -> lczero.api.v1.MatchGame
	29, // 42: lczero.api.v1.SprtProgress.pairs:type_name -> lczero.api.v1.SprtPairReport
	27, // 43: lczero.api.v1.TuningPairResult.game1:type_name -> lczero.api.v1.MatchGame
	27, // 44: lczero.api.v1.TuningPairResult.game2:type_name -> lczero.api.v1.MatchGame
	31, // 45: lczero.api.v1.TuningParamSetResult.pairs:type_name -> lczero.api.v1.TuningPairResult
	32, // 46: lczero.api.v1.TuningProgress.results:type_name -> lczero.api.v1.TuningParamSetResult
	18, // 47: lczero.api.v1.AuthService.MigrateCredentials:input_type -> lczero.api.v1.MigrateCredentialsRequest
	19, // 48: lczero.api.v1.AuthService.GetAnonymousToken:input_type -> lczero.api.v1.AnonymousTokenRequest
	21, // 49: lczero.api.v1.TaskService.GetNextTask:input_type -> lczero.api.v1.TaskRequest
	22, // 50: lczero.api.v1.TaskService.ReportProgress:input_type -> lczero.api.v1.ProgressReport
	20, // 51: lczero.api.v1.AuthService.MigrateCredentials:output_type -> lczero.api.v1.AuthResponse
	20, // 52: lczero.api.v1.AuthService.GetAnonymousToken:output_type -> lczero.api.v1.AuthResponse
	11, // 53: lczero.api.v1.TaskService.GetNextTask:output_type -> lczero.api.v1.TaskResponse
	23, // 54: lczero.api.v1.TaskService.ReportProgress:output_type -> lczero.api.v1.ProgressResponse
	51, // [51:55] is the sub-list for method output_type
	47, // [47:51] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_api_v1_lczero_proto_init() }
func file_api_v1_lczero_proto_init() {
	if File_api_v1_lczero_proto != nil {
		return
	}
	file_api_v1_lczero_proto_msgTypes[4].OneofWrappers = []any{
		(*TimeControl_TimeBased_)(nil),
		(*TimeControl_NodesPerMove)(nil),
	}
	file_api_v1_lczero_proto_msgTypes[5].OneofWrappers = []any{
		(*TaskResponse_Training)(nil),
		(*TaskResponse_Match)(nil),
		(*TaskResponse_Sprt)(nil),
		(*TaskResponse_Tuning)(nil),
	}
	file_api_v1_lczero_proto_msgTypes[16].OneofWrappers = []any{
		(*ProgressReport_Training)(nil),
		(*ProgressReport_Match)(nil),
		(*ProgressReport_Sprt)(nil),
		(*ProgressReport_Tuning)(nil),
	}
	file_api_v1_lczero_proto_msgTypes[23].OneofWrappers = []any{}
	file_api_v1_lczero_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_lczero_proto_rawDesc), len(file_api_v1_lczero_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_v1_lczero_proto_goTypes,
		DependencyIndexes: file_api_v1_lczero_proto_depIdxs,
		EnumInfos:         file_api_v1_lczero_proto_enumTypes,
		MessageInfos:      file_api_v1_lczero_proto_msgTypes,
	}.Build()
	File_api_v1_lczero_proto = out.File
	file_api_v1_lczero_proto_goTypes = nil
	file_api_v1_lczero_proto_depIdxs = nil
}
